version: 0.2

phases:

  install:
    commands:
      - echo "Installing dependencies..."
      - pip install flask

  pre_build:
    commands:
      - echo "Starting EAIT CI Pipeline..."

  build:
    commands:
      - echo "Building EAIT Student Portal"

  post_build:
    commands:
      - echo "Build completed successfully"
